---
- name: Reload Jenkins service
  service:
    name: jenkins
    state: reloaded
  register: reloaded

- name: Restart Jenkins service
  service:
    name: jenkins
    state: restarted
  when: (reloaded is not defined) or not reloaded.changed

- name: Reset reloaded.changed variable
  set_fact:
    reloaded: { 'changed': false }
  listen: Reload Jenkins service
