---
jenkins_version: '2.390'

jenkins_ip: "{{ ansible_host }}"
jenkins_port: 8080
jenkins_admin_email: admin@example.com

jenkins_user: jenkins
jenkins_api_token_name: ansible_token
jenkins_api_token_uuid: '048eed1d-b393-40d3-9381-7974bcc062b4'

jenkins_java_options: '-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false'

jenkins_plugins: []

jenkins_jobs: []

jenkins_url: "http://{{ jenkins_ip }}:{{ jenkins_port }}"
jenkins_local_url: "http://127.0.0.1:{{ jenkins_port }}"
jenkins_home: /var/lib/jenkins
