---
- name: Copy main config file
  template:
    src: config.xml.j2
    dest: "{{ jenkins_home }}/config.xml"
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins service

- name: Copy location config file
  template:
    src: jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: "{{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml"
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins service
