---
- name: Set Jenkins Java options
  lineinfile:
    dest: /usr/lib/systemd/system/jenkins.service
    regexp: '^Environment="JAVA_OPTS='
    line: "Environment=\"JAVA_OPTS={{ jenkins_java_options }}\""
