---
- name: Create secrets directory
  file:
    path: "{{ jenkins_home }}/secrets"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: Copy secrets directory content
  copy:
    src: "{{ playbook_dir }}/files/credentials/secrets/"
    dest: "{{ jenkins_home }}/secrets/"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy credentials and secrets to the root of Jenkins directory
  copy:
    src: "{{ playbook_dir }}/files/credentials/{{ item }}"
    dest: "{{ jenkins_home }}/{{ item }}"
    owner: jenkins
    group: jenkins
    mode: 0644
  with_items:
    - credentials.xml
    - secret.key
    - secret.key.not-so-secret
