---
- name: Print jenkins_url with local_action
  become: false
  local_action:
    module: debug
    var: jenkins_url
    verbosity: 1

- name: Print inventory_hostname with local_action
  become: false
  local_action:
    module: debug
    var: inventory_hostname
    verbosity: 1

- name: Print ansible_host with local_action
  become: false
  local_action:
    module: debug
    var: ansible_host
    verbosity: 1

- name: Create GitHub webhook
  become: false
  local_action:
    module: community.general.github_webhook
    repository: "{{ github_repo }}"
    url: "http://{{ inventory_hostname }}:{{ jenkins_port }}/github-webhook/"
    content_type: json
    events:
      - push
    user: "{{ github_user }}"
    token: "{{ github_api_token }}"
