---
- import_tasks: "service/start.yml"

- import_tasks: "wait-startup.yml"

# For some reason Jenkins doesn't install plugins right after start, even though it returns code 200
# TODO: retry installing plugins instead of waiting beforehand
#       or find another way to check if Jenkins is ready
- name: Pause while Jenkins is starting
  pause:
    seconds: 60

- name: Set quiet mode
  uri:
    url: "{{ jenkins_local_url }}/quietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true

- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    url: "{{ jenkins_local_url }}"
    timeout: 60
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  with_items: "{{ jenkins_plugins }}"
  notify:
    - Restart Jenkins service

- name: Make sure that all plugins were downloaded
  wait_for:
    path: "{{ jenkins_home }}/plugins/{{ item }}.jpi"
    timeout: 1
  with_items: "{{ jenkins_plugins }}"

- name: Flush handlers after installing plugins
  meta: flush_handlers
