---
- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    url: "{{ jenkins_local_url }}"
    timeout: 60
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  with_items: "{{ jenkins_plugins }}"
  notify:
    - Restart Jenkins service

- name: Make sure that all plugins were downloaded
  wait_for:
    path: "{{ jenkins_home }}/plugins/{{ item }}.jpi"
    timeout: 1
  with_items: "{{ jenkins_plugins }}"
