---
- name: Make sure that .ssh directory is created and has right permissions
  file:
    path: "{{ jenkins_home }}/.ssh"
    state: directory
    mode: 0700
    owner: jenkins
    group: jenkins

# TODO: abstract from GitHub
# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
- name: Add GitHub to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "github.com {{ item }}"
    path: "{{ jenkins_home }}/.ssh/known_hosts"
    state: present
  with_items:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

# TODO: known_hosts (agents, webserver)

- name: Make sure that know_hosts file has right permissions
  file:
    path: "{{ jenkins_home }}/.ssh/known_hosts"
    state: file
    mode: 0644
    owner: jenkins
    group: jenkins
