---

- import_tasks: "install.yml"

- import_tasks: "config-initial/main.yml"

- import_tasks: "install-plugins.yml"

- import_tasks: "config-other/main.yml"

- import_tasks: "known-hosts.yml"

- import_tasks: "service/start-enable.yml"

- import_tasks: "github-webhook.yml"
