---

- import_tasks: "install.yml"

- import_tasks: "config-initial/main.yml"

- import_tasks: "install-plugins.yml"

- import_tasks: "config-other/main.yml"

- import_tasks: "known-hosts.yml"

- import_tasks: "service/start-enable.yml"

- import_tasks: "github-webhook.yml"

- import_tasks: "wait-startup.yml"

- name: Make sure quiet mode is disabled
  uri:
    url: "{{ jenkins_local_url }}/cancelQuietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true

# TODO: trigger first build with ansible
