---
- include_vars: vault.yml

- import_tasks: "install.yml"

- import_tasks: "configure.yml"

- name: Reload and start Jenkins service
  service:
    name: jenkins
    state: reloaded

- name: Wait for Jenkins to start up
  uri:
    url: "{{ local_jenkins_url }}"
    status_code: 200
    timeout: 5
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  register: jenkins_service_status
  retries: 30
  delay: 1
  until: jenkins_service_status is not failed

# TODO: install plugins

# TODO: restart
