---
- include_vars: vault.yml

- import_tasks: "install.yml"

- import_tasks: "configure.yml"

- name: Flush handlers after initial Jenkins configuration
  meta: flush_handlers

- import_tasks: "service/start.yml"

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_local_url }}"
    status_code: 200
    timeout: 5
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  register: jenkins_service_status
  retries: 10
  delay: 1
  until: jenkins_service_status is not failed

- name: Set quiet mode
  uri:
    url: "{{ jenkins_local_url }}/quietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true

- import_tasks: "install-plugins.yml"

# TODO: Only stop if configs will be changed
- import_tasks: "service/stop.yml"

# TODO: configure nodes

# TODO: configure secrets

- import_tasks: "configure-jobs.yml"

- name: Flush handlers after configuring plugins, nodes, secrets and jobs
  meta: flush_handlers

- import_tasks: "service/start.yml"
