---
- import_tasks: "install.yml"

# TODO: Only stop if configs will be changed
- import_tasks: service/stop.yml

- import_tasks: "config/service.yml"
  notify:
    - Reload Jenkins service

- import_tasks: "config/jenkins.yml"
  notify:
    - Restart Jenkins service

- import_tasks: "config/users.yml"
  notify:
    - Restart Jenkins service

- name: Flush handlers after initial Jenkins configuration
  meta: flush_handlers

- import_tasks: "service/start.yml"

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_local_url }}"
    status_code: 200
    timeout: 5
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  register: jenkins_service_status
  retries: 10
  delay: 1
  until: >
      'status' in jenkins_service_status and
      jenkins_service_status['status'] == 200

# For some reason Jenkins doesn't install plugins right after start, even though it returns code 200
# TODO: retry installing plugins instead of waiting beforehand
#       or find another way to check if Jenkins is ready
- name: Pause while Jenkins is starting
  pause:
    seconds: 60

- name: Set quiet mode
  uri:
    url: "{{ jenkins_local_url }}/quietDown"
    method: POST
    headers:
      Content-Type: "text/xml"
    status_code: 200,302
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true

- import_tasks: "install-plugins.yml"

# TODO: Only stop if configs will be changed
- import_tasks: "service/stop.yml"

- import_tasks: "config/nodes.yml"
  notify:
    - Restart Jenkins service

- import_tasks: "config/secrets.yml"
  notify:
    - Restart Jenkins service

# TODO: config settings (e.g. io.jenkins.plugins.artifact_manager_jclouds.s3.S3BlobStoreConfig.xml)

- import_tasks: "config/jobs.yml"
  notify:
    - Restart Jenkins service

- import_tasks: "known-hosts.yml"

- name: Flush handlers after configuring plugins, nodes, secrets and jobs
  meta: flush_handlers

# TODO: enable jenkins service
- import_tasks: "service/start.yml"

- import_tasks: "github-webhook.yml"
