---
- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_local_url }}"
    status_code: 200
    timeout: 5
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
  register: jenkins_service_status
  retries: 10
  delay: 1
  until: >
      'status' in jenkins_service_status and
      jenkins_service_status['status'] == 200
